# Values used for the deployed application.
replicaCount: 1
service:
  name: upp-next-video-annotations-mapper
env:
  APP_NAME: "Next Video Annotations Mapper"
  APP_SYSTEM_CODE: up-nvam
  APP_PORT: 8080
  PANIC_GUIDE: https://dewey.ft.com/up-nvam.html
  Q_GROUP: upp-next-video-annotations-mapper
  Q_READ_TOPIC: NativeCmsMetadataPublicationEvents
  Q_WRITE_TOPIC: ConceptAnnotations
  KAFKA_LAG_TOLERANCE: 120
  LOG_LEVEL: "INFO"
