# Default values for upp-next-video-annotations-mapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  isResilient: "false"
replicaCount: 1
image:
  repository: coco/upp-next-video-annotations-mapper
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 128Mi
  limits:
    memory: 300Mi
env:
  APP_NAME: ""
  APP_SYSTEM_CODE: ""
  APP_PORT: ""
  PANIC_GUIDE: ""
  Q_GROUP: ""
  Q_READ_TOPIC: ""
  Q_WRITE_TOPIC: ""
